# Use postgres/example user/password credentials
version: '3'

services:
  auth: 
    build: ./backend/auth

    depends_on:
      - db

    env_file: 
      - ./backend/auth/.env

    networks:
      - default

    ports:
      - 5000:5000

    volumes:
      - ./backend/auth:/app

    restart: always

  db:
    image: postgres:14-alpine

    restart: always

    networks:
      - default

    env_file: 
      - backend\auth\.env

    environment:
      - POSTGRES_USERNAME:"nancyadmin"
      - POSTGRES_PASSWORD:"nncyadmn"
      - POSTGRES_DB:"user_data"

    ports:
      - '5432:5432'

    volumes:
      - db-data:/var/lib/postgresql/data/

    
volumes:
  db-data: 


  